version: "3.8"
services:
  brain:
    build:
      context: services/brain
      args:
        BRAIN_VERSION: 0.1.30
    environment:
      - LOG_LEVEL=debug
    restart: unless-stopped
    volumes:
      - brain_data:/app/data
  web3signer:
    depends_on:
      flyway:
        condition: service_completed_successfully
    security_opt:
      - seccomp:unconfined
    build:
      context: services/web3signer
      args:
        WEB3SIGNER_VERSION: 25.4.1
        STAKER_SCRIPTS_VERSION: v0.1.2
        POSTGRES_USER: postgres
    environment:
      JAVA_OPTS: "-Xmx6g"
      EXTRA_OPTS: ""
      WEB3SIGNER_VERTX_WORKER_POOL_SIZE: "20"
    volumes:
      - web3signer_data:/data
    restart: unless-stopped
  flyway:
    build:
      context: services/flyway
      args:
        WEB3SIGNER_VERSION: 25.4.1
        POSTGRES_USER: postgres
    depends_on:
      postgres:
        condition: service_started
    restart: on-failure
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.alpine
      args:
        WEB3SIGNER_VERSION: 25.4.1
        DATA_DIR: /var/lib/postgresql/data
        POSTGRES_USER: postgres
    user: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  brain_data: {}
  web3signer_data: {}
  postgres_data: {}
